name: PR
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      repo:
        description: repo
        required: true
        default: https://github.com/Onekey-Project/OnekeyPro
      level:
        description: Logging Level
        required: true
        default: INFO
        type: choice
        options:
          - CRITICAL
          - FATAL
          - ERROR
          - WARNING
          - WARN
          - INFO
          - DEBUG
          - NOTSET
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: Onekey-Project/OnekeyPro
          token: ${{ secrets.token }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          python3 pr.py --repo ${{ github.event.inputs.repo || 'https://github.com/Onekey-Project/OnekeyPro' }} -t ${{ secrets.token }} -l ${{ github.event.inputs.level || 'INFO' }}